apiVersion: v1
kind: Service
metadata:
  name: {{ include "library-management-system.fullname" . }}
  labels:
    {{- include "library-management-system.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "library-management-system.selectorLabels" . | nindent 4 }}
