apiVersion: v1
kind: Namespace
metadata:
  name: library-system
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: library-system
type: Opaque
data:
  mysql-root-password: bGlicmFyeV9yb290X3Bhc3N3b3Jk  # library_root_password
  mysql-password: bGlicmFyeV9wYXNzd29yZA==  # library_password
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: library-system
data:
  mysql-database: library_db
  mysql-user: library_user
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: library-system
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-root-password
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: mysql-database
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: library-system
  labels:
    app: mysql
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql 